# Generated by Django 6.0 on 2025-12-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='cruds_usuario',
        ),
    ]
