# Generated by Django 6.0 on 2025-12-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0002_alter_usuario_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
