# Generated by Django 6.0 on 2025-12-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0003_usuario_password_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuariopending',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=50)),
                ('edad', models.IntegerField(default=0)),
                ('email', models.CharField(default='', max_length=100)),
                ('token', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'cruds_usuariopending',
            },
        ),
    ]
