# Generated by Django 6.0 on 2025-12-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0004_usuariopending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
